# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'DevOps-Connection'
    subscriptionId: '83e3d384-0c74-460e-a9ef-8a0f3d3d17d7'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'lab-rg'
    location: 'East US'
    templateLocation: 'URL of the file'
    csmFileLink: 'https://raw.githubusercontent.com/Yogeeswarvk/azure-quickstart-templates/master/quickstarts/microsoft.compute/vm-simple-linux/azuredeploy.json'
    csmParametersFileLink: 'https://raw.githubusercontent.com/Yogeeswarvk/azure-quickstart-templates/master/quickstarts/microsoft.compute/vm-simple-linux/azuredeploy.parameters.json'
    deploymentMode: 'Incremental'